# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Le Monde à Venir
email: hexiea.feint@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  "On a besoin de changer." We need to change. Let's be exacting in our actions.
  Let's paint the future together. Ensemble.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
gitlab_username:  hexiea_feint

# Outputting
permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown
exclude: ["README.md"]

# Precommit checks
pre-commit:
  - check: FrontMatterVariableExists
    variables: ['basename', 'short_title', 'title']
  - check: FrontMatterVariableIsNotDuplicate
    variables: ['basename', 'short_title', 'title']
  - check: FrontMatterVariableMeetsLengthRequirements
    variables: ['title', 'basename||20', 'short_title||20']
  - check: NoDuplicateTags
