# config.yml

backend:
  name: gitlab
  repo: hexiea_feint/monde-a-venir

media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
